### ISSUE TITLE
change users

### ISSUE THREAD

**Issue by fxfactorial** [iteratehackerspace/machine-setup#1]
the script is meant to be run as root but the `apm install` part needs to be run for the `iterate` user.

**Comment by mike1808** [comment]
Will `sudo -H -u iterate npm install` do the trick?

**Comment by fxfactorial** [comment]
I think `-H` is a sudo thing, not `su`

```
su: invalid option -- 'H'
Usage: su [options] [LOGIN]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd
```

**Comment by mike1808** [comment]
I googled more and got this:

`su - iterate -c "npm install"`

**Comment by fxfactorial** [comment]
That sounds correct, wanna try this github feature, programmatically close this issue with a commit,

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by fxfactorial** [comment]
@mike1808 oh, also, can you change `set -uou pipefail` to `set -euo pipefail`
